[RFR] Two players
marmelab/quixo-react-native pull request #4
Opened 2019-06-21 12:52 UTC by HALLERPierre

# TODO
- [ ] Add join game screen
- [ ] Add assign team API
- [ ] Add instructions

# Result
![2-p](https://user-images.githubusercontent.com/6030943/59923637-2f0b7100-9434-11e9-9ffd-60d21b3ffbd2.gif)

2019-06-21 13:07 UTC, zyhou requested changes
Can you test the component and the `game/actions.js` file ?

2019-06-21 13:07 UTC, zyhou commented on api/tests.js/game/game.test.js
> +      expect(destinations.length).toEqual(exepectedDestinations.length);
`toBe` instead of `toEqual`

2019-06-21 13:07 UTC, zyhou commented on quixo-react-native/game/actions.js
> +  await AsyncStorage.getItem(`@Quixo-game-${id}`);
parse the team result here

2019-06-21 13:07 UTC, zyhou commented on quixo-react-native/game/actions.js
> +  return () => clearInterval(intervalId);
+1

2019-06-21 13:07 UTC, zyhou commented on quixo-react-native/screens/GameScreen.js
> +const getInstructions = (team, isPlaying) => {
Move the component in another file. Rename to `<Instructions />`

2019-06-21 13:07 UTC, zyhou commented on quixo-react-native/screens/GameScreen.js
> +  useEffect(fetchMyTeam(id, dispatch), [game.id]);
why not `[id]` ?

2019-06-21 13:07 UTC, zyhou commented on quixo-react-native/screens/GameScreen.js
> +                handlePress={() => handlePressCube({ x, y })}
remove this func

2019-06-21 14:07 UTC, Kmaschta commented on quixo-react-native/screens/GameScreen.js
> +        <Text style={styles.instructionsText}>You're a spectator </Text>
Apostrophe are breaking GitHub diff. Nothing to really worry about, but it's nice if you wrap "You're" with a template literal next time. `{"You're"}`

2019-06-24 07:32 UTC, zyhou approved these changes

2019-06-24 07:32 UTC, merged